scene:
  type: InTheWild
  attributes:
    img_path: ../dataset/coco/images/val2017/000000033638.jpg
  annotations_path: ../dataset/coco/random_annotations/batch_run_200/33638.json
  save_dir: ../experimental_results/dp_trellis_debug/000000033638
  K: []
run:
  use_enhancement: true
  only_foreground: true
  single_object: false
  reproject: false
  depth_edge_threshold: 0.0001
  amodal_completion: our
  obj_rec: tl
  depth:
    metric: depthpro
    relative: null
  segmentation:
    holistic: entityv2
    fg_bg: clipseg
    merge_masks:
      dilation: 7
      threshold: 0.5
    tagger: ovsam
  calibration:
    intrinsics: perspectivefields
    pose: null
  clip_bg: false
